// 图像映射：人物/诗词/章回 配图优先来自 hlm.yanghuide.kdns.fr（用户自有站点，水墨风格）；
// 地点立轴图亦来自该站（/images/places/）；个别无站点图的回退 Wikimedia Commons 公有领域插图。
export const IMAGES = {
  "baoyu": "assets/baoyu.webp",
  "daiyu": "assets/daiyu.webp",
  "baochai": "assets/baochai.webp",
  "xifeng": "assets/xifeng.webp",
  "jiamu": "assets/jiamu.webp",
  "jiazheng": "assets/jiazheng.webp",
  "wangfuren": "assets/wangfuren.webp",
  "xiangyun": "assets/xiangyun.webp",
  "miaoyu": "assets/miaoyu.webp",
  "yanchun": "assets/yanchun.webp",
  "tanchun": "assets/tanchun.webp",
  "yingchun": "assets/yingchun.webp",
  "xichun": "assets/xichun.webp",
  "keqing": "assets/keqing.webp",
  "liwan": "assets/liwan.webp",
  "qiaojie": "assets/qiaojie.webp",
  "xiren": "assets/xiren.webp",
  "qingwen": "assets/qingwen.webp",
  "xiangling": "assets/xiangling.webp",
  "zijuan": "assets/zijuan.webp",
  "pingr": "assets/pingr.webp",
  "yuanyang": "assets/yuanyang.webp",
  "jialian": "assets/jialian.webp",
  "xuepan": "assets/xuepan.webp",
  "zhenshiyin": "assets/zhenshiyin.webp",
  "yucun": "assets/yucun.webp",
  "liaolao": "assets/liaolao.webp",
  "xianglian": "assets/xianglian.webp",
  "jiangyuhan": "assets/jiangyuhan.webp",
  "mingyan": "assets/mingyan.webp",
  "daguanyuan": "assets/daguanyuan.jpg",
  "yihongyuan": "assets/yihongyuan.webp",
  "xiaoxiangguan": "assets/xiaoxiangguan.webp",
  "hengwuyuan": "assets/hengwuyuan.webp",
  "daoxiangcun": "assets/daoxiangcun.webp",
  "longcuan": "assets/longcuan.webp"
};
